11:04:42.398 Running build in Washington, D.C., USA (East) – iad1
11:04:42.398 Build machine configuration: 2 cores, 8 GB
11:04:42.522 Cloning github.com/lukabandur/mystorija (Branch: main, Commit: 718959a)
11:04:43.165 Cloning completed: 643.000ms
11:04:43.800 Restored build cache from previous deployment (5887gcrr226awuyyt42QSLZ4pR52)
11:04:44.032 Running "vercel build"
11:04:44.052 Vercel CLI 54.2.0
11:04:44.259 Detected `pnpm-lock.yaml` 9 which may be generated by pnpm@9.x or pnpm@10.x
11:04:44.259 Using pnpm@10.x based on project creation date
11:04:44.259 To use pnpm@9.x, manually opt in using corepack (https://vercel.com/docs/deployments/configure-a-build#corepack)
11:04:44.263 Running "install" command: `pnpm install --no-frozen-lockfile`...
11:04:45.825 Progress: resolved 0, reused 0, downloaded 1, added 0
11:04:46.828 Progress: resolved 5, reused 0, downloaded 4, added 0
11:04:47.641  WARN  deprecated next@15.3.6: This version has a security vulnerability. Please upgrade to a patched version. See https://nextjs.org/blog/security-update-2025-12-11 for more details.
11:04:47.843 Progress: resolved 9, reused 0, downloaded 8, added 0
11:04:48.852 Progress: resolved 63, reused 0, downloaded 39, added 0
11:04:49.853 Progress: resolved 73, reused 0, downloaded 42, added 0
11:04:50.853 Progress: resolved 75, reused 0, downloaded 45, added 0
11:04:51.212 Already up to date
11:04:51.219 Progress: resolved 87, reused 0, downloaded 61, added 0, done
11:04:51.267 
11:04:51.273 Done in 6.9s using pnpm v10.28.0
11:04:51.308 Detected Next.js version: 15.3.6
11:04:51.316 Running "pnpm run build"
11:04:51.610 
11:04:51.611 > mystorija@1.0.0 build /vercel/path0
11:04:51.611 > next build
11:04:51.611 
11:04:52.348    ▲ Next.js 15.3.6
11:04:52.348 
11:04:52.350    Linting and checking validity of types ...
11:04:52.466    Creating an optimized production build ...
11:04:54.958 Failed to compile.
11:04:54.959 
11:04:54.959 ./pages/en.js
11:04:54.959 Error:   x Expected '}', got 'is'
11:04:54.959      ,-[/vercel/path0/pages/en.js:106:1]
11:04:54.960  103 |         <div style={{ textAlign:"center", marginBottom:40 }}>
11:04:54.960  104 |           <div className="section-label" style={{ textAlign:"center" }}>For everyone who wants to renovate</div>
11:04:54.960  105 |           <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(26px,5vw,38px)", lineHeight:1.25 }}>
11:04:54.960  106 |             {Inspiration is everywhere –<br /><em style={{ color:"var(--accent)" }}>Mystorija helps you get it done</em>}
11:04:54.960      :                          ^^
11:04:54.960  107 |           </h2>
11:04:54.960  108 |         </div>
11:04:54.960  109 |         <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))", gap:16, marginBottom:50 }}>
11:04:54.960      `----
11:04:54.961 
11:04:54.961 Caused by:
11:04:54.961     Syntax Error
11:04:54.961 
11:04:54.961 Import trace for requested module:
11:04:54.961 ./pages/en.js
11:04:54.963 
11:04:54.963 ./pages/en/app.js
11:04:54.963 Module not found: Can't resolve '../lib/supabase'
11:04:54.963 
11:04:54.963 https://nextjs.org/docs/messages/module-not-found
11:04:54.963 
11:04:54.963 ./pages/landing.js
11:04:54.963 Error:   x Expected '}', got 'ist'
11:04:54.964      ,-[/vercel/path0/pages/landing.js:106:1]
11:04:54.964  103 |         <div style={{ textAlign:"center", marginBottom:40 }}>
11:04:54.964  104 |           <div className="section-label" style={{ textAlign:"center" }}>Für jeden der renovieren möchte</div>
11:04:54.964  105 |           <h2 style={{ fontFamily:"'Playfair Display',serif", fontSize:"clamp(26px,5vw,38px)", lineHeight:1.25 }}>
11:04:54.964  106 |             {Inspiration ist überall –<br /><em style={{ color:"var(--accent)" }}>Mystorija hilft dir umzusetzen</em>}
11:04:54.965      :                          ^^^
11:04:54.965  107 |           </h2>
11:04:54.965  108 |         </div>
11:04:54.965  109 |         <div style={{ display:"grid", gridTemplateColumns:"repeat(auto-fit,minmax(280px,1fr))", gap:16, marginBottom:50 }}>
11:04:54.965      `----
11:04:54.965 
11:04:54.965 Caused by:
11:04:54.965     Syntax Error
11:04:54.971 
11:04:54.971 Import trace for requested module:
11:04:54.971 ./pages/landing.js
11:04:54.971 
11:04:54.979 
11:04:54.980 > Build failed because of webpack errors
11:04:55.010  ELIFECYCLE  Command failed with exit code 1.
11:04:55.036 Error: Command "pnpm run build" exited with 1
